### ISSUE TITLE
not connected

### ISSUE THREAD

**Issue by dydfrancis** [ASHWIN990/ADB-Toolkit#1]
Since i started this adb of a thing i have not seen any connected device why right from phonsploit and sdo many other it always been no device connected please i will like to no more about this adb tools thanks dydfrancis10gmail.com

**Comment by ASHWIN990** [comment]
## Hello @dydfrancis  
Can you please elaborate your problem, so i can suggest you what to do, you can write me at ashwinisahu990@gmail.com and provide SS also if possible.

#### BTW, things you must have for connecting wirelessly  
* You must update the ADB-Toolkit to it's latest version v2.3 
* Make sure your device has USB debugging ON
* Make Sure you and your device which has ADB-Toolkit installed are connected in the same network
