### ISSUE TITLE
Dosen't need root

### ISSUE THREAD

**Issue by DoubleRainbowXT** [ASHWIN990/ADB-Toolkit#24]
The install and ADB panel script dosen't need root at all, i deleted the root checks and it worked.
It also said I didn't have adb even tho i did and after i deleted that check too it worked perfectly fine.

**Comment by GiblerDribbler** [comment]
How did you deleted root checks?

**Comment by DoubleRainbowXT** [comment]
Idk if your trolling me but i used a text editing tool called nano on the file also it's checks are broken and it doesn't need root

**Comment by DoubleRainbowXT** [comment]
Heres what i deleted to use it without root cuz you dont need it
if [ $(id -u) -ne 0 ]; then
        echo "THIS SCRIPT MUST BE RAN AS ROOT"
        exit 1
fi

if [ -d $PWD/.temp/ ]
    then
        echo -e "YOU HAVE THE .temp DIRECTORY" && clear
    else
        echo -e "PLEASE INSTALL THE TOOL IF NOT INSTALLED OR IF INSTALLED MAKE A '.temp' DIRECTORY FIRST" && exit
fi



adb_check=$(which adb) 

if [ "$?" == 0 ]; then
    echo -e "ADB IS INSTALLED\n"
    echo -e "INITALIZING ADB\n"
else
    echo -e "\nADB IS NOT INSTALLED, RUN THE INSTALLATION SCRIPT OR TRY INSTALLING 'ADB' MANUALLY"
    exit 1
fi


adb_check=$(which fastboot)

if [ "$?" == 0 ]; then
    echo -e "FASTBOOT IS INSTALLED\n"
    echo -e "INITALIZING FASTBOOT\n"
else
    echo -e "\nFASTBOOT IS NOT INSTALLED, RUN THE INSTALLATION SCRIPT OR TRY INSTALLING 'FASTBOOT' MANUALLY"
    exit 1
fi

**Comment by GiblerDribbler** [comment]
> Idk if your trolling me
No, I wasn't trolling 😅
I just happens to be a little bit of noob for these things, so I didn't genuinely knew, how to delete those root checks, but I appreciate your responses for clearing that out 🙂👍
And while I was trying to figure it out myself, I happened to find another way of bypassing those checks by installing ADB-Toolkit to Ubuntu in Termux 😀

**Comment by DoubleRainbowXT** [comment]
What? The script dosent need root i can just git clone then nano to remove the checks and then i can use it i dont know why you made root checks.

**Comment by GiblerDribbler** [comment]
I didn't. I just bypassed them, because I didn't have any other way of getting past them during that time.

**Comment by DoubleRainbowXT** [comment]
So you didn't make this tool?

**Comment by GiblerDribbler** [comment]
What? No. Someone named ASHWIN990 made this tool, not me.

**Comment by DoubleRainbowXT** [comment]
Ohh

**Comment by DoubleRainbowXT** [comment]
Issue closed
