### ISSUE TITLE
The toolkit options need to be corrected for MAC !

### ISSUE THREAD

**Issue by vinayakbjoshi** [ASHWIN990/ADB-Toolkit#3]
HI,

   First of all a fantastic toolkit developed!

On mac, looks like menu items need to be corrected.
![image](https://user-images.githubusercontent.com/5460075/89004291-75155280-d31f-11ea-88b4-e6f96d6d0838.png)

**Comment by ASHWIN990** [comment]
Thanks for using it 😊
Can you tell me which shell you are using, in MacOS Apple has replaced the default shell to ZSH and this tool is purely written in Bash.

So tell me which Shell you are running.

**Comment by Ajdin94622** [comment]
Please give command????
